export default [
	{
		id: 1,
		name: 'Spaghetti Carbonara',
		description: 'Delicious pasta dish with creamy sauce',
		author: 'John Doe',
		rating: 4,
		img: '',
	},
	{
		id: 2,
		name: 'Chicken Tikka Masala',
		description: 'Spicy Indian chicken curry',
		author: 'Jane Smith',
		rating: 5,
		img: '',
	},
	{
		id: 3,
		name: 'Margherita Pizza',
		description: 'Classic Italian pizza with tomatoes and mozzarella',
		author: 'Mike Johnson',
		rating: 3,
		img: '',
	},
	{
		id: 4,
		name: 'Sushi Rolls',
		description: 'Japanese sushi with various fillings',
		author: 'Emily Brown',
		rating: 4,
		img: '',
	},
	{
		id: 5,
		name: 'Pad Thai',
		description: 'Thai stir-fried noodles with shrimp',
		author: 'David Wilson',
		rating: 2,
		img: '',
	},
	{
		id: 6,
		name: 'Cheeseburger',
		description: 'Juicy burger with cheese and toppings',
		author: 'Sarah Davis',
		rating: 5,
		img: '',
	},
	{
		id: 7,
		name: 'Caesar Salad',
		description: 'Fresh salad with Caesar dressing and croutons',
		author: 'Chris Martinez',
		rating: 4,
		img: '',
	},
	{
		id: 8,
		name: 'Tacos',
		description: 'Mexican tacos with flavorful fillings',
		author: 'Jessica Taylor',
		rating: 3,
		img: '',
	},
	{
		id: 9,
		name: 'Ramen',
		description: 'Japanese noodle soup with pork and veggies',
		author: 'Daniel Anderson',
		rating: 4,
		img: '',
	},
	{
		id: 10,
		name: 'Chocolate Cake',
		description: 'Decadent dessert for chocolate lovers',
		author: 'Lisa Thomas',
		rating: 5,
		img: '',
	},
	{
		id: 11,
		name: 'Lasagna',
		description: 'Classic Italian layered pasta dish',
		author: 'Andrew Clark',
		rating: 4,
		img: '',
	},
	{
		id: 12,
		name: 'Steak with Mashed Potatoes',
		description: 'Juicy steak served with creamy mashed potatoes',
		author: 'Emma White',
		rating: 5,
		img: '',
	},
	{
		id: 13,
		name: 'Pancakes with Berries',
		description: 'Fluffy pancakes topped with fresh berries',
		author: 'Michael Brown',
		rating: 4,
		img: '',
	},
	{
		id: 14,
		name: 'Chicken Caesar Wrap',
		description: 'Grilled chicken wrapped in a Caesar salad',
		author: 'Olivia Harris',
		rating: 3,
		img: '',
	},
	{
		id: 15,
		name: 'Fish Tacos',
		description: 'Crispy fish tacos with slaw and avocado',
		author: 'Nathan Evans',
		rating: 4,
		img: '',
	},
	{
		id: 16,
		name: 'Vegetable Stir-Fry',
		description: 'Healthy stir-fried vegetables in a savory sauce',
		author: 'Sophia Green',
		rating: 2,
		img: '',
	},
	{
		id: 17,
		name: 'BBQ Ribs',
		description: 'Tender BBQ ribs with a smoky flavor',
		author: 'Ethan Johnson',
		rating: 5,
		img: '',
	},
	{
		id: 18,
		name: 'Shrimp Pasta',
		description: 'Creamy shrimp pasta with garlic and herbs',
		author: 'Ava Martinez',
		rating: 3,
		img: '',
	},
	{
		id: 19,
		name: 'Vegetarian Curry',
		description: 'Spicy curry with assorted vegetables',
		author: 'William Davis',
		rating: 4,
		img: '',
	},
	{
		id: 20,
		name: 'Fruit Salad',
		description: 'Colorful fruit salad with a tangy dressing',
		author: 'Madison Clark',
		rating: 5,
		img: '',
	},
	{
		id: 21,
		name: 'Stuffed Bell Peppers',
		description: 'Bell peppers stuffed with rice and veggies',
		author: 'Logan White',
		rating: 4,
		img: '',
	},
	{
		id: 22,
		name: 'Beef Stir-Fry',
		description: 'Savory beef stir-fried with vegetables',
		author: 'Avery Adams',
		rating: 3,
		img: '',
	},
	{
		id: 23,
		name: 'Mushroom Risotto',
		description: 'Creamy risotto with flavorful mushrooms',
		author: 'Elijah Taylor',
		rating: 4,
		img: '',
	},
	{
		id: 24,
		name: 'Greek Salad',
		description: 'Traditional Greek salad with feta cheese',
		author: 'Zoe Anderson',
		rating: 5,
		img: '',
	},
	{
		id: 25,
		name: 'Apple Pie',
		description: 'Homemade apple pie with a flaky crust',
		author: 'Carter Brown',
		rating: 4,
		img: '',
	},
];
