export default [
	{
		id: 1,
		name: 'Spaghetti Carbonara',
		description: 'Delicious pasta dish with creamy sauce',
		author: 'John Doe',
		rating: 4,
		img: '',
		ingredients: [
			'200g spaghetti',
			'100g pancetta or guanciale',
			'2 large eggs',
			'50g grated pecorino cheese',
			'Salt and black pepper',
			'Olive oil',
		],
		steps: [
			'Cook the spaghetti in a large pot of boiling salted water until al dente.',
			'In a separate pan, cook the pancetta or guanciale until crisp and golden.',
			'In a bowl, whisk together the eggs, grated pecorino cheese, salt, and pepper.',
			'Drain the cooked spaghetti and add it to the pan with the cooked pancetta or guanciale.',
			'Remove the pan from heat and quickly stir in the egg and cheese mixture, allowing the residual heat to cook the eggs and create a creamy sauce.',
			'Serve the spaghetti carbonara immediately, garnished with extra grated cheese and black pepper.',
		],
	},
	{
		id: 2,
		name: 'Chicken Tikka Masala',
		description: 'Spicy Indian chicken curry',
		author: 'Jane Smith',
		rating: 5,
		img: '',
		ingredients: [
			'500g chicken breast, cut into cubes',
			'1 cup plain yogurt',
			'2 tbsp tikka masala paste',
			'1 onion, finely chopped',
			'2 cloves garlic, minced',
			'1 inch ginger, grated',
			'1 can diced tomatoes',
			'1/2 cup heavy cream',
			'Fresh cilantro, for garnish',
			'Salt and pepper to taste',
			'Cooked rice or naan bread for serving',
		],
		steps: [
			'Marinate the chicken pieces in yogurt and tikka masala paste for at least 30 minutes.',
			'In a large pan, heat oil and sauté onions, garlic, and ginger until fragrant.',
			'Add marinated chicken and cook until browned.',
			'Stir in diced tomatoes and simmer for 15-20 minutes.',
			'Add heavy cream, salt, and pepper to taste.',
			'Garnish with fresh cilantro and serve hot with cooked rice or naan bread.',
		],
	},
	{
		id: 3,
		name: 'Margherita Pizza',
		description: 'Classic Italian pizza with tomatoes and mozzarella',
		author: 'Mike Johnson',
		rating: 3,
		img: '',
		ingredients: [
			'Pizza dough',
			'Tomato sauce',
			'Fresh mozzarella cheese',
			'Fresh basil leaves',
			'Olive oil',
			'Salt and pepper',
		],
		steps: [
			'Preheat your oven to the highest setting with a pizza stone if available.',
			'Roll out the pizza dough into a circle.',
			'Spread tomato sauce evenly over the dough, leaving a small border around the edges.',
			'Tear fresh mozzarella into pieces and place them on top of the sauce.',
			'Add fresh basil leaves and drizzle olive oil over the pizza.',
			'Season with salt and pepper to taste.',
			'Bake in the preheated oven until the crust is golden and the cheese is bubbly and browned.',
			'Slice and serve hot, garnished with additional fresh basil if desired.',
		],
	},
	{
		id: 4,
		name: 'Sushi Rolls',
		description: 'Japanese sushi with various fillings',
		author: 'Emily Brown',
		rating: 4,
		img: '',
	},
	{
		id: 5,
		name: 'Pad Thai',
		description: 'Thai stir-fried noodles with shrimp',
		author: 'David Wilson',
		rating: 2,
		img: '',
	},
	{
		id: 6,
		name: 'Cheeseburger',
		description: 'Juicy burger with cheese and toppings',
		author: 'Sarah Davis',
		rating: 5,
		img: '',
	},
	{
		id: 7,
		name: 'Caesar Salad',
		description: 'Fresh salad with Caesar dressing and croutons',
		author: 'Chris Martinez',
		rating: 4,
		img: '',
	},
	{
		id: 8,
		name: 'Tacos',
		description: 'Mexican tacos with flavorful fillings',
		author: 'Jessica Taylor',
		rating: 3,
		img: '',
	},
	{
		id: 9,
		name: 'Ramen',
		description: 'Japanese noodle soup with pork and veggies',
		author: 'Daniel Anderson',
		rating: 4,
		img: '',
	},
	{
		id: 10,
		name: 'Chocolate Cake',
		description: 'Decadent dessert for chocolate lovers',
		author: 'Lisa Thomas',
		rating: 5,
		img: '',
	},
	{
		id: 11,
		name: 'Lasagna',
		description: 'Classic Italian layered pasta dish',
		author: 'Andrew Clark',
		rating: 4,
		img: '',
	},
	{
		id: 12,
		name: 'Steak with Mashed Potatoes',
		description: 'Juicy steak served with creamy mashed potatoes',
		author: 'Emma White',
		rating: 5,
		img: '',
	},
	{
		id: 13,
		name: 'Pancakes with Berries',
		description: 'Fluffy pancakes topped with fresh berries',
		author: 'Michael Brown',
		rating: 4,
		img: '',
	},
	{
		id: 14,
		name: 'Chicken Caesar Wrap',
		description: 'Grilled chicken wrapped in a Caesar salad',
		author: 'Olivia Harris',
		rating: 3,
		img: '',
	},
	{
		id: 15,
		name: 'Fish Tacos',
		description: 'Crispy fish tacos with slaw and avocado',
		author: 'Nathan Evans',
		rating: 4,
		img: '',
	},
	{
		id: 16,
		name: 'Vegetable Stir-Fry',
		description: 'Healthy stir-fried vegetables in a savory sauce',
		author: 'Sophia Green',
		rating: 2,
		img: '',
	},
	{
		id: 17,
		name: 'BBQ Ribs',
		description: 'Tender BBQ ribs with a smoky flavor',
		author: 'Ethan Johnson',
		rating: 5,
		img: '',
	},
	{
		id: 18,
		name: 'Shrimp Pasta',
		description: 'Creamy shrimp pasta with garlic and herbs',
		author: 'Ava Martinez',
		rating: 3,
		img: '',
	},
	{
		id: 19,
		name: 'Vegetarian Curry',
		description: 'Spicy curry with assorted vegetables',
		author: 'William Davis',
		rating: 4,
		img: '',
	},
	{
		id: 20,
		name: 'Fruit Salad',
		description: 'Colorful fruit salad with a tangy dressing',
		author: 'Madison Clark',
		rating: 5,
		img: '',
	},
	{
		id: 21,
		name: 'Stuffed Bell Peppers',
		description: 'Bell peppers stuffed with rice and veggies',
		author: 'Logan White',
		rating: 4,
		img: '',
	},
	{
		id: 22,
		name: 'Beef Stir-Fry',
		description: 'Savory beef stir-fried with vegetables',
		author: 'Avery Adams',
		rating: 3,
		img: '',
	},
	{
		id: 23,
		name: 'Mushroom Risotto',
		description: 'Creamy risotto with flavorful mushrooms',
		author: 'Elijah Taylor',
		rating: 4,
		img: '',
	},
	{
		id: 24,
		name: 'Greek Salad',
		description: 'Traditional Greek salad with feta cheese',
		author: 'Zoe Anderson',
		rating: 5,
		img: '',
	},
	{
		id: 25,
		name: 'Apple Pie',
		description: 'Homemade apple pie with a flaky crust',
		author: 'Carter Brown',
		rating: 4,
		img: '',
	},
];
